#!/bin/bash

DOTFILESDIR="$(readlink -e "$(dirname "$0")")"
export DOTFILESDIR

YELLOW="\E[33;1m"
CYAN="\E[36;1m"
WHITE="\E[37;1m"
RESET="\E[0m"

info () {
  echo -e ${YELLOW}"$1"${RESET}
}

run_scripts () {
  for script in "$DOTFILESDIR"/**/$1; do
    echo -e ${CYAN}Executing ${WHITE}$script${RESET}
    sh -c "$script"
  done
}

# Create symbolic links
info "Creating symbolic links"
ln -s "$DOTFILESDIR/bin" "$HOME/bin"
for target in "$DOTFILESDIR"/**/*.symlink; do
  link=$HOME/.$(basename "${target%.*}")
  ln -s "$target" "$link"
done

# Run preinstall scripts
info "Running preinstall scripts"
run_scripts preinstall.sh

# Install packages
info "Installing packages"
packages=($(find "$DOTFILESDIR" -name packages -type f -exec cat {} + | sort -u | xargs))
sudo apt-get update && sudo apt-get install -y "${packages[@]}"

# Initialize submodules
info "Initializing submodules"
git submodule update --init --recursive

# Run install scripts
info "Running install scripts"
run_scripts install.sh

# Run postinstall scripts
info "Running postinstall scripts"
run_scripts postinstall.sh
